version: "3.8"
services:      
  web:
    build:
      context: ./
      target: production
    depends_on: 
      postgres: 
        condition: service_healthy
    ports:
      - "80:3000"
    environment:
      NODE_ENV: production
      HOST: 0.0.0.0
      PORT: 3000

  postgres:
    image: postgres:13
    container_name: db
    ports:
      - 5432:5432
    env_file:
      .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pg_data:
