version: "3.8"
services:      
  web:
    depends_on: 
      postgres: 
        condition: service_healthy
    restart: always 
    build:
      context: ./
      target: production
      dockerfile: dockerfiles/Dockerfile
    ports:
      - "80:3000"
    environment:
      HOST: 0.0.0.0
      PORT: 3000
      NODE_ENV: production
      POSTGRES_URL: postgres://postgres:postgres@db:5432/server

  postgres:
    image: postgres:13
    container_name: db
    restart: always 
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: server
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pg_data:
