version: "3.8"
services:
  prisma-studio:
    container_name: prisma-studio
    image: timothyjmiller/prisma-studio:latest
    restart: unless-stopped
    env_file: 
      .env
    ports:
      - 5555:5555
      
  web:
    build:
      context: ./dockerfiles
      target: dev
    depends_on: 
      postgres: 
        condition: service_healthy
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
    env_file:
      .env

  postgres:
    image: postgres:13
    container_name: db
    ports:
      - 5432:5432
    env_file:
      .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pg_data:
