name: 'deploy'

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Cloning repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      
      - name: Delete dockerfile
        run: rm -rf Dockerfile

      - name: Push to dokku
        uses: dokku/github-action@master
        with:
          git_remote_url: 'ssh://dokku@em.kevinludwig.dev:22/em'
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          git_push_flags: "--force"